# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: csac

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'v{{ incpatch .Version }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
dockers:
  - image_templates:
      - 'neobaran/{{.ProjectName}}:{{.Version}}'
      - 'neobaran/{{.ProjectName}}:latest'
      - 'ghcr.io/neobaran/{{.ProjectName}}:{{.Version}}'
      - 'ghcr.io/neobaran/{{.ProjectName}}:latest'
      - 'ccr.ccs.tencentyun.com/neobaran/{{.ProjectName}}:latest'
      - 'ccr.ccs.tencentyun.com/neobaran/{{.ProjectName}}:{{.Version}}'
    dockerfile: Dockerfile.goreleaser
