# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: csac

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

dockers:
  - image_templates:
      - 'neobaran/{{ .ProjectName }}:{{ .Version }}'
      - 'neobaran/{{ .ProjectName }}:latest'
      - 'ghcr.io/neobaran/{{ .ProjectName }}:{{ .Version }}'
      - 'ghcr.io/neobaran/{{ .ProjectName }}:latest'
      - 'ccr.ccs.tencentyun.com/neobaran/{{ .ProjectName }}:latest'
      - 'ccr.ccs.tencentyun.com/neobaran/{{ .ProjectName }}:{{ .Version }}'
    build_flag_templates:
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.description=Cloud Service Auto Cert'
      - '--label=org.opencontainers.image.url={{ .GitURL }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.licenses=MIT'
